export const gbpLocation = {
  storeName: "Green Pentagon Cannabis",
  domain: "www.greenpentagoncannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "1267 Queen St W, Toronto, ON M6K 2J2",
  streetAddress: "1267 Queen St W",
  postalCode: "M6K 2J2",
  phone: "(416) 388-5765",
  phoneIntl: "+14163885765",
  neighborhood: "Parkdale / Queen West",
  nearbyAreas: ["Queen St W", "Lansdowne", "Parkdale", "Dufferin", "Liberty Village", "Roncesvalles", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6415588",
  longitude: "-79.4312674",
  hours: ["Open Daily: 10:00 AM - 12:00 AM"],
  seoTitle: "Green Pentagon Cannabis | Weed Dispensary in Toronto",
  metaDescription: "Green Pentagon Cannabis is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Queen St W", "Lansdowne", "Parkdale"],
  introVariant: "Green Pentagon Cannabis is a local weed dispensary at 1267 Queen St W in Toronto. Adults 19+ can browse flower tiers and category pages for pre-rolls, edibles, vapes, concentrates, cigarettes, and accessories before visiting.",
  neighborhoodDescription: "Located in the vibrant Parkdale / Queen West district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking is available along Queen Street West",
  transitNote: "Accessible via the 501 Queen streetcar and local TTC bus routes.",
  sectionTitle: "Serving Customers Near Parkdale in Toronto"
};
