// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Green Pentagon Cannabis",
  domain: "greenpentagoncannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "1267 Queen St W, Toronto, ON M6K 2J2",
  streetAddress: "1267 Queen St W",
  postalCode: "M6K 2J2",
  phone: "(416) 388-5765",
  phoneIntl: "+14163885765",
  neighborhood: "Parkdale / Queen West",
  nearbyAreas: ["Queen St W", "Lansdowne", "Parkdale", "Dufferin", "Liberty Village", "Roncesvalles", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://greenpentagoncannabis.com/",
  mapEmbedUrl: "https://maps.google.com/maps?q=Green%20Pentagon%20Cannabis%201267%20Queen%20St%20W%2C%20Toronto%2C%20ON%20M6K%202J2&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6415588",
  longitude: "-79.4312674",
  hours: ["Open Daily: 10:00 AM - 12:00 AM"],
  seoTitle: "Green Pentagon Cannabis | Weed Dispensary in Toronto",
  metaDescription: "Green Pentagon Cannabis is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Queen St W", "Lansdowne", "Parkdale"],
  introVariant: "Green Pentagon Cannabis is a local weed dispensary in Toronto, located at 1267 Queen St W. We serve adults 19+ looking for quality weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories. Whether you are searching for a weed dispensary near Parkdale / Queen West, a cannabis store in Toronto, or a local weed shop close to Lansdowne, our friendly team is here to help you find the right product.",
  neighborhoodDescription: "Located in the vibrant Parkdale / Queen West district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking is available along Queen Street West",
  transitNote: "Accessible via the 501 Queen streetcar and local TTC bus routes.",
  sectionTitle: "Serving Customers Near Parkdale in Toronto"
};
