export const gbpLocation = {
  storeName: "Green Pentagon Cannabis",
  domain: "www.greenpentagoncannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "1267 Queen St W, Toronto, ON M6K 2J2",
  streetAddress: "1267 Queen St W",
  postalCode: "M6K 2J2",
  phone: "+1 (437) 290-3657",
  phoneIntl: "+14372903657",
  neighborhood: "Parkdale / Queen West",
  nearbyAreas: ["Queen St W", "Parkdale", "Parkdale Village", "Dufferin", "Brock", "Queen and Dufferin", "TTC 501"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "/visit",
  mapEmbedUrl: "https://www.google.com/maps?q=1267+Queen+St+W,+Toronto,+ON+M6K+2J2&output=embed",
  latitude: "43.6415588",
  longitude: "-79.4312674",
  hours: ["Open Daily: 10:00 AM - 12:00 AM"],
  seoTitle: "Green Pentagon Cannabis | Parkdale / Queen West Dispensary",
  metaDescription: "Walk-in cannabis shop at 1267 Queen St W for Parkdale and Queen West. Adults 19+. Open Daily: 10:00 AM - 12:00 AM. Call +1 (437) 290-3657.",
  localLandmarks: ["Queen St W", "Parkdale Village", "Dufferin", "Gladstone Hotel"],
  introVariant: "Green Pentagon Cannabis is a walk-in dispensary at 1267 Queen St W on Queen West / Parkdale. Adults 19+ can browse flower collections and category pages for pre-rolls, edibles, vapes, concentrates, cigarettes, and accessories before visiting.",
  neighborhoodDescription: "The storefront sits on Queen Street West just west of Dufferin, where West Queen West turns into Parkdale Village, with the 501 streetcar at the curb.",
  parkingNote: "Evening street parking on Queen Street West and laterals such as Close, Cowan, and Dunn; Green P around Queen & Dufferin when the curb is full.",
  transitNote: "501 Queen streetcar (Dufferin and Brock stops), 29 Dufferin bus, Dufferin Gate Loop toward Exhibition Place.",
  sectionTitle: "Serving Customers Near Parkdale and Queen West"
};
